---
deployment:
  tasks:
    - /bin/mkdir -p /home/icanalog/ranchiwebsite.com/projects/rtc
    - /bin/cp -rf ts-app/dist/* /home/icanalog/ranchiwebsite.com/projects/rtc/
    - /bin/cp -f ts-app/dist/.htaccess /home/icanalog/ranchiwebsite.com/projects/rtc/.htaccess

